
//もし選択肢をカスタマイズするのであればここにobjectを追加。
export default QuestionParams = {
  alergy:{
      title: "アレルギー",
      index: "1",
      imagePath: "../images/alergy.png",
      question0: "症状はない",
      question1: "一時的な皮膚の赤み・発疹・ かゆみなどがある",
      question2: "息苦しさ・のどの詰まり感・ 全身に発疹などがある",
      question3: "息ができない・ぜえぜえする, 大量の冷や汗・めまいがある",
  },
  hirou:{
      title: "疲労感",
      index: "2",
      imagePath: "../images/hirou.png",
      question0: "疲労感はない",
      question1: "疲労感はあるが,休めばよくなる",
      question2: "疲労感があり,休んでもよくならない・身の回りのことはなんとかできる",
      question3: "疲労感があり,休んでもよくならない・身の回りのことができないことが多い",
  },
  syoku:{
      title: "食欲",
      index: "3",
      imagePath: "../images/syoku.png",
      question0: "食欲はある",
      question1: "少し食欲はないが,ほぼ普段通り食事がとれる",
      question2: "食欲はないが,なんとか食事はとれる",
      question3: "まったく食欲がなく,食事や水分がほとんどとれない",
  },
  hakike:{
      title: "吐き気",
      index: "4",
      imagePath: "../images/hakike.png",
      question0: "吐き気はない",
      question1: "軽い吐き気はあるが,ほぼ普段通り食事がとれる",
      question2: "吐き気はあるが,なんとか食事はとれる",
      question3: "強い吐き気があり,食事や水分がほとんどとれない",
  },
  outo:{
      title: "嘔吐",
      index: "5",
      question0: "嘔吐はない",
      question1: "1日に,1～2回嘔吐する",
      question2: "1日に,3～5回嘔吐する",
      question3: "1日に,6回以上嘔吐する",
  },
  geri:{
      title: "下痢",
      index: "6",
      question0: "下痢はない",
      question1: "1日に,1～3回下痢する・ストーマからの排泄量が少し増える",
      question2: "1日に,4～6回下痢する・ストーマからの排泄量が増える",
      question3: "1日に,7回以上下痢する・ストーマからの排泄量がかなり増える",
  },
  benpi:{
      title: "便秘",
      index: "7",
      question0: "自然に排便がある",
      question1: "排便はないが,苦痛ではない・下剤を時々使用する",
      question2: "排便がなく,苦痛がある・下剤を毎日使用している・身の回りのことはなんとかできる",
      question3: "下剤を毎日使用しても, 排便がなく, 強い苦痛がある",
  },
  kounaienn:{
      title: "口内炎",
      index: "8",
      question0: "口内炎はない",
      question1: "軽い口内炎はあるが,               ほぼ普段通り食事がとれる",
      question2: "口内炎の痛みはあるが,           なんとか食事はとれる",
      question3: "口内炎の強い痛みがあり,         ほとんど食事がとれない",
  },
  teasi:{
      title: "手足の感覚",
      index: "9",
      question0: "手や足にしびれはない",
      question1: "手や足に軽いしびれがある",
      question2: "手や足にしびれがある・      　　　身の回りのことはなんとかできる",
      question3: "手や足に,強いしびれがある・身の回りのことができないことが多い",
  },
  mikaku:{
      title: "味覚の変化",
      index: "10",
      question0: "普段と比べ味の感じ方に変わりはない",
      question1: "本来の味と少し違って感じるが,ほぼ普段通り食事がとれる",
      question2: "本来の味が感じられないため,普段とは違う食事で, なんとか過ごしている",
      question3: "",
  },
  namidame:{
      title: "涙目",
      index: "11",
      question0: "涙で視界がぼやけることはない",
      question1: "気にならない程度に涙で視界がぼやけて見えることがある",
      question2: "涙で視界がぼやけて見えるが,身の回りのことはなんとかできる",
      question3: "涙で視界がぼやけて見えるため,身の回りのことができないことが多い",
  },
  teasisyoukougun:{
      title: "手足症候群",
      index: "12",
      question0: "手や足の皮膚に,腫れや赤みなどはない",
      question1: "手や足のひりひり感・腫れ・    赤みなどはあるが,痛みはない",
      question2: "手や足の腫れ・水ぶくれ・     ひび割れなどがあり,痛みがある",
      question3: "手や足の腫れ・水ぶくれ・     ひび割れなどがあり,強い痛みがある",
  },
  sikiso:{
      title: "色素沈着",
      index: "13",
      question0: "色素沈着（黒ずみ）はない",
      question1: "気にならない程度の色素沈着（黒ずみ）がある",
      question2: "部分的,または広範囲に色素沈着（黒ずみ）がある・気持ちの落ち込みがある",
      question3: "",
  },


}
